name: "DOCUMENTATION"

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Latex
      run: |
        sudo apt install texlive-latex-extra
        sudo apt install dvipng
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --progress-bar off .
        pip install -r doc/requirements.txt
    - name: Compute documentation
      run: |
        mkdir -p tmp/doc
        sphinxdoc -v 2 -p . -n mmbench -o tmp/doc
        cd tmp/doc
        make raw-html
        cd ../..
    - name: Upload documentation as an artifact
      uses: actions/upload-artifact@v2
      with: 
        name: html-documentation
        retention-days: 15
        path: |
            tmp/doc/build/html
